export const loginLanguageDTO = {
    username: 'Username or Email',
    usernamePlaceholder:'Username',
    userNameValidationMessage:'Username is required',
    password: 'Password',
    passwordPlaceholder:'Password',
    passwordValidationMessage:'Password is required',
    title: 'Login',
    submit: 'Submit',
    loginFailed: 'Authentication failed',
    requiredCommon: '',
    signIn: "Sign In"

}
export const dashboardLanguageDTO = {
    meetings: 'Meetings',
    tasks: 'Tasks',
}
export const settingsLanguageDTO = {
    changeLanguage: 'Change language',
    logout: 'Sign out',
    changeCompany: 'Change company',
    changePassword: 'Change password',
    helpLineNumber: 'Call helpline',

}
export const taskLanguageDTO = {
    myTasks: 'MyTasks',
    tasks: 'Tasks',
    dueDate: 'Due Date',
    createDate: 'Create Date',
    createTask: 'Create Task',
    business: 'Business',
    assignTo: 'Assign To',
    assignToValidationMessage: 'Please a select executive',
    assignToPlaceholder: 'Select Executive',
    title: 'Title',
    titlePlaceholder: 'Enter Task Title',
    titleValidationMessage: 'Title is required',
    dueDatePlaceholder: 'Enter Due Date',
    createDatePlaceholder: 'Enter Create Date',
    description: 'Description',
    descriptionPlaceholder: 'Enter Task Description',
    submit: 'Submit',
    executiveListTitle: 'EXECUTIVES',
    executive:'Executive',
    executiveSearchPlaceholder:'Search Executive',
    taskSearchPlaceholder:'Search Task',
}
export const meetingLanguageDTO = {
    createMeeting: 'Create Meeting',
    purpose: 'Purpose',
    purposePlaceholder: 'Select Meeting Purpose',
    purposeValidationMessage: 'Purpose is required',
    contact: 'Contact',
    contactPlaceholder: 'Select Contact',
    contactValidationMessage: 'Contact is required',
    title: 'Title',
    titlePlaceholder: 'Enter Meeting Title',
    titleValidationMessage: 'Title is required',
    description: 'Description',
    descriptionPlaceholder: 'Enter Description',
    schedule: 'Schedule',
    startMeeting: 'Start Meeting',
    meetingDateAndTime:'Date & Time',
    meetingDateAndTimePlaceholder:'Enter Schedule Meeting Date & Time',
    meetingDateAndTimeValidationMessage:'Date & Time is required',
    scheuleMeeting:'Schedule',
    contactListTitle:'CONTACTS',
    contactSearchPlaceholder:'Search Contact',
}
export const commonLanguageDTO={
    success:'Success',
    error:'Error',
    saveSuccessMessage:'Successfully saved',
    saveErrorMessage:'Saving failed',
    saveValidationMessage:'Please correct the indicated items',
    filterActionHeading:'FILTER & SORT',
    filterCaption:'FILTERS',
    sortCaption:'Sort',
    sortRecent:'Recently Added',
    sortAscending:'A to Z',
    sortDescending:'Z to A',
    clear:'Clear',
    apply:'Apply',
    
}
export const businessSelectLanguageDTO = {
    label: 'Business',
    placeholder: 'Select Business',
    requiredValidationMessage:'Business is required',
}
export const businessLanguageDTO={
    filterTypeLabel:'Business Type',
    filterTypePlaceholder:'Select Type',
    filterCityLabel:'Business City',
    filterCityPlaceholder:'Select City',
    filterCountryLabel:'Business Country',
    filterCountryPlaceholder:'Select Country',
    cityListTitle:'CITIES',
    countryListTitle:'COUNTRIES',
    countrySearchPlaceholder:'Search Countries',
    citySearchPlaceholder:'Search Cities',
    businessSearchPlaceholder:'Search Business',
    businessTypeListTitle:'Select Business Type',
}